# Generated by Django 5.2.9 on 2025-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unikalus raktažodis šablono parinkimui kode.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Pavadinimas admin'e.", max_length=150)),
                (
                    "subject",
                    models.CharField(help_text="Tema su {{ kintamaisiais }}.", max_length=255),
                ),
                ("body_text", models.TextField(blank=True, help_text="Grynas tekstas (fallback).")),
                (
                    "body_html",
                    models.TextField(blank=True, help_text="HTML versija su {{ kintamaisiais }}."),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "El. laiško šablonas",
                "verbose_name_plural": "El. laiškų šablonai",
                "ordering": ["key"],
            },
        ),
    ]
