# Generated by Django 5.2.9 on 2025-12-31 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hero_text_html", models.TextField(blank=True)),
                ("text_after_footer", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="site/footer/hero/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footer blokai",
            },
        ),
        migrations.CreateModel(
            name="HeaderMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "link",
                    models.CharField(
                        blank=True, help_text="URL arba vidinis kelias.", max_length=255
                    ),
                ),
                ("is_dropdown", models.BooleanField(default=False)),
                ("icon_svg", models.TextField(blank=True, help_text="Pilnas SVG fragmentas.")),
                ("image", models.ImageField(blank=True, null=True, upload_to="site/header/menu/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Header meniu",
                "verbose_name_plural": "Header meniu",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HeroBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("hero_text_html", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="site/hero/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero blokas",
                "verbose_name_plural": "Hero blokai",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SiteHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta_title", models.CharField(blank=True, max_length=80)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("description_html", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/header/logo/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Header blokas",
                "verbose_name_plural": "Header blokai",
            },
        ),
        migrations.CreateModel(
            name="FooterColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "column_type",
                    models.CharField(
                        choices=[("linklist", "Nuorodų sąrašas"), ("html_text", "HTML tekstas")],
                        max_length=20,
                    ),
                ),
                ("link_title", models.CharField(blank=True, max_length=255)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("html_block", models.TextField(blank=True)),
                (
                    "footer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="sitecontent.footer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer stulpelis",
                "verbose_name_plural": "Footer stulpeliai",
                "ordering": ["footer", "order"],
            },
        ),
        migrations.CreateModel(
            name="HeaderDropdownItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("icon_svg", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="site/header/dropdown/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropdown_items",
                        to="sitecontent.headermenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dropdown nuoroda",
                "verbose_name_plural": "Dropdown nuorodos",
                "ordering": ["menu", "order"],
            },
        ),
        migrations.AddField(
            model_name="headermenu",
            name="header",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="sitecontent.siteheader",
            ),
        ),
    ]
