# Generated by Django 5.2.9 on 2025-12-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="recipe",
            name="meta_title",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="recipe",
            name="video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="description_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
